# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0349d3817395b4788da5732fc3f37810615e367b285927b45b3b23d53183bbfece855edccf385897420f95c7c468864a8b6c401a90cc075323f9c06d40ee87a0

test:
  secret_key_base: 4a1614b525b715de77fd8c3ab52003d8e1c656835c56661567cea61f4ec09bdbbff458213b808d8ea35582557e26ec1ddb2b8d007c249cf3f6d315b404efe1d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
